name: Push nextcloud Image

on:
  push:
    tags:
      - v*
    branches:
      - master

env:
  IMAGE_NAME: nextcloud

jobs:
  image:
    name: Build nextcloud Image
    runs-on: ubuntu-latest
    steps:
      - name: Set IMAGE_TAG env (on push to master branch)
        run: echo "IMAGE_TAG=latest" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/master'
      - name: Set IMAGE_TAG env (on tag)
        run: echo "IMAGE_TAG=${GITHUB_REF:11}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags')
      - uses: actions/checkout@v2
      - name: Set PHP_VERSION env
        run: echo "PHP_VERSION=$(cat ./nextcloud/php_version)" >> $GITHUB_ENV
      - name: Set NEXTCLOUD_VERSION env
        run: echo "NEXTCLOUD_VERSION=$(cat ./nextcloud/nextcloud_version)" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: traptitech
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./nextcloud
          push: true
          platforms: linux/amd64
          build-args: |
            NEXTCLOUD_VERSION=${{ env.NEXTCLOUD_VERSION }}
            PHP_VERSION=${{ env.PHP_VERSION }}
          tags: |
            ghcr.io/traptitech/${{ env.IMAGE_NAME }}:latest
            ghcr.io/traptitech/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
