name: Push nextcloud Image

on:
  push:
    tags:
      - v*
    branches:
      - master

env:
  IMAGE_NAME: nextcloud

jobs:
  image:
    name: Build nextcloud Image
    runs-on: ubuntu-latest
    steps:
      - name: Set IMAGE_TAG env (on push to master branch)
        run: echo "IMAGE_TAG=latest" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/master'
      - name: Set IMAGE_TAG env (on tag)
        run: echo "IMAGE_TAG=${GITHUB_REF:11}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags')
      - uses: actions/checkout@v2
      - name: Set PHP_VERSION env
        run: echo "PHP_VERSION=$(cat ./nextcloud/php_version)" >> $GITHUB_ENV
      - name: Set NEXTCLOUD_VERSION env
        run: echo "NEXTCLOUD_VERSION=$(cat ./nextcloud/nextcloud_version)" >> $GITHUB_ENV
      - name: Login GitHub Registry
        run: docker login docker.pkg.github.com -u traPtitech -p ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image
        run: docker build --build-arg NEXTCLOUD_VERSION=${NEXTCLOUD_VERSION} --build-arg PHP_VERSION=${PHP_VERSION} -t docker.pkg.github.com/traptitech/nextcloud-builder/${IMAGE_NAME}:${IMAGE_TAG} ./nextcloud
      - name: Push image to GitHub Registry
        run: docker push docker.pkg.github.com/traptitech/nextcloud-builder/${IMAGE_NAME}:${IMAGE_TAG}
